# Generated by Django 5.2 on 2025-05-22 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extractednote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='back',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='front',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-22 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question',
            field=models.TextField(default='Default question'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.studysession')),
            ],
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
