# Generated by Django 5.2 on 2025-05-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_back_flashcard_answer_remove_flashcard_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractednote',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
