# Generated by Django 5.2 on 2025-06-01 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_flashcard_session_flashcardset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='note_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='core.extractednote')),
            ],
        ),
    ]
