# Generated by Django 5.2 on 2025-05-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_extractednote_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSpeechAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='tts_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts_audio', to='core.studysession')),
            ],
        ),
    ]
