# Generated by Django 5.1.6 on 2025-06-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_quiz_title_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
