# Generated by Django 5.1.6 on 2025-06-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
