# Generated by Django 5.2 on 2025-05-22 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_uploadedfile_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_files_to_session', to='core.studysession'),
        ),
    ]
