# Generated by Django 5.1.6 on 2025-06-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_useranswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mc', 'Multiple Choice'), ('tf', 'True/False'), ('long', 'Long Answer'), ('fib', 'Fill in the Blank'), ('short', 'Short Answer')], max_length=10),
        ),
    ]
