# Generated by Django 5.1.6 on 2025-06-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_noteaudio'),
        ('core', '0009_alter_question_question_type'),
    ]

    operations = [
    ]
