# Generated by Django 5.2 on 2025-06-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20250604_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
