# Generated by Django 5.2 on 2025-06-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_useranswer_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractednote',
            name='file',
        ),
        migrations.RemoveField(
            model_name='extractednote',
            name='text',
        ),
        migrations.AddField(
            model_name='extractednote',
            name='cleaned_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='extractednote',
            name='original_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='extractednote',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.uploadedfile'),
        ),
    ]
